# Generated by Django 4.2.20 on 2025-06-15 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Eatery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('lunch', 'lunch'), ('canteen', 'canteen'), ('restraunt', 'restraunt')], max_length=50)),
                ('cuisine', models.CharField(blank=True, max_length=200)),
                ('price', models.TextField(blank=True, default='Write Your Price Here')),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('pincode', models.DecimalField(decimal_places=0, max_digits=6)),
                ('latitude', models.CharField(blank=True, max_length=20)),
                ('longitude', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtype', models.CharField(max_length=20)),
                ('desp', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('price', models.PositiveIntegerField(null=True)),
                ('availability', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('NOT-AVAILABLE', 'NOT-AVAILABLE')], default='AVAILABLE', max_length=50)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='room')),
                ('info', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ammenities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.attributes')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.location')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.rcategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='product_images/')),
                ('attach_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='rental.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='MenuAttach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.FileField(blank=True, upload_to='product_images/')),
                ('attach_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eatery_menu', to='rental.eatery')),
            ],
        ),
        migrations.CreateModel(
            name='EateryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='product_images/')),
                ('attach_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eatery_images', to='rental.eatery')),
            ],
        ),
        migrations.AddField(
            model_name='eatery',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.location'),
        ),
        migrations.AddField(
            model_name='eatery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
