# Generated by Django 4.2.20 on 2025-06-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='ammenities',
        ),
        migrations.AddField(
            model_name='rooms',
            name='ammenities',
            field=models.ManyToManyField(related_name='ammenities', to='rental.attributes'),
        ),
    ]
