# Generated by Django 4.2.20 on 2025-06-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_remove_rooms_ammenities_rooms_ammenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuattach',
            name='attach_from',
        ),
        migrations.RemoveField(
            model_name='roomimages',
            name='attach_from',
        ),
        migrations.AddField(
            model_name='eatery',
            name='image',
            field=models.ImageField(blank=True, upload_to='food_images/'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='image',
            field=models.ImageField(blank=True, upload_to='room_images/'),
        ),
        migrations.DeleteModel(
            name='EateryImages',
        ),
        migrations.DeleteModel(
            name='MenuAttach',
        ),
        migrations.DeleteModel(
            name='RoomImages',
        ),
    ]
