# Generated by Django 4.2.20 on 2025-06-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceProfile',
            new_name='SellerProfile',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('renter', 'Renter'), ('seller', 'Seller')], max_length=20),
        ),
    ]
